* Doom Emacs Config

** Packages

Add the =atom-one-dark= theme
#+BEGIN_SRC elisp :tangle packages.el
(package! atom-one-dark-theme)
#+END_SRC


Disable =doom-themes= since they are not used.
#+BEGIN_SRC elisp :tangle packages.el
(package! doom-themes :disable t)
#+END_SRC

** Config
Enable lexical binding for faster speed and better scoping
#+BEGIN_SRC elisp
;; -*- lexical-binding: t -*-
#+END_SRC

Set the full name and mail address for the packages that need this
#+BEGIN_SRC elisp
(setq user-full-name "Arjun S."
      user-mail-address "arjunsenthilvel1@gmail.com")
#+END_SRC

Set the font to Victor Mono and Noto Sans TC.
#+BEGIN_SRC elisp
(setq doom-font "Victor Mono-16"
      doom-variable-pitch-font "Noto Sans TC-9")
#+END_SRC

Load the =atom-one-dark= theme.
#+BEGIN_SRC elisp
(setq doom-theme 'atom-one-dark)
#+END_SRC

Configure =org= to use the =doom= directory for storing org files.
#+BEGIN_SRC elisp
(setq org-directory (concat doom-private-dir "org/"))
#+END_SRC


Disable line numbers due to laggy scrolling.
#+BEGIN_SRC elisp
(setq display-line-numbers-type nil)
#+END_SRC



=use-package= declaration for =atom-one-dark=
#+BEGIN_SRC elisp
(use-package! atom-one-dark-theme)
#+END_SRC

Disable wrapping of long lines.
#+BEGIN_SRC elisp
(visual-line-mode nil)
#+END_SRC

Load custom =treemacs= theme (icons from vscode-material-icon-theme)
Set the =treemacs= faces to /Noto Sans TC/
#+BEGIN_SRC elisp
(after! treemacs
  (treemacs-resize-icons 16)
  (load! "treemacs-theme/theme")
  (dolist (face '(treemacs-git-unmodified-face
                  treemacs-git-modified-face
                  treemacs-git-renamed-face
                  treemacs-git-ignored-face
                  treemacs-git-untracked-face
                  treemacs-git-added-face
                  treemacs-git-conflict-face
                  treemacs-directory-face
                  treemacs-directory-collapsed-face
                  treemacs-file-face
                  treemacs-tags-face))
    (set-face-attribute face nil :family "Noto Sans TC" :height 90)))
#+END_SRC


Tweak some default settings for =lsp-ui=.
(Enable =lsp-ui-doc= and others)
#+BEGIN_SRC elisp
(after! lsp-ui
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-max-width 150
        lsp-ui-doc-include-signature t
        lsp-eldoc-hook nil
        lsp-ui-doc-delay 1.25))

#+END_SRC

Disable the signature in =lsp-mode= at bottom.
#+BEGIN_SRC elisp
(after! lsp-mode
  (setq lsp-signature-auto-activate nil
        lsp-signature-render-documentation nil))
#+END_SRC


Make company give suggestions faster.
#+BEGIN_SRC elisp
(after! company
  (setq company-idle-delay 0
        company-minimum-prefix-length 1))
#+END_SRC

Use =rainbow-delimiters-mode= in all =prog-mode= buffers
#+BEGIN_SRC elisp
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
#+END_SRC
