(defface treemacs-all-the-icons-root-face
  '((t (:inherit font-lock-string-face)))
  "Face used for the root icon in all-the-icons theme."
  :group 'treemacs-faces)
(defvar treemacs-all-the-icons-tab (if (bound-and-true-p treemacs-all-the-icons-tab-font)
                                       (propertize "\t" 'face `((:family ,treemacs-all-the-icons-tab-font)))
                                     "\t"))


(treemacs-modify-theme "Default"
  :icon-directory (concat user-emacs-directory "lisp/treemacs-theme/icons")
  :config
  (progn
    (treemacs-create-icon
     :icon (format "%s%s%s" treemacs-all-the-icons-tab (all-the-icons-octicon "repo"
                                                                              :height 1.2
                                                                              :v-adjust -0.1
                                                                              :face 'treemacs-all-the-icons-root-face)
                   treemacs-all-the-icons-tab)
     :extensions (root))

    (treemacs-create-icon :file "html.png" :extensions ("htm" "xhtml" "html_vm" "asp"))
    (treemacs-create-icon :file "pug.png" :extensions (".pug-lintrc" ".pug-lintrc.js" ".pug-lintrc.json"))
    (treemacs-create-icon :file "markdown.png" :extensions ("md" "markdown" "rst"))
    (treemacs-create-icon :file "blink.png" :extensions ("blink"))
    (treemacs-create-icon :file "css.png" :extensions ("css"))
    (treemacs-create-icon :file "sass.png" :extensions ("scss" "sass"))
    (treemacs-create-icon :file "less.png" :extensions ("less"))
    (treemacs-create-icon :file "json.png" :extensions (".jscsrc" ".jshintrc" "composer.lock" ".jsbeautifyrc" ".esformatter" "cdp.pid" ".mjmlconfig" "json"))
    (treemacs-create-icon :file "jinja.png" :extensions ("jinja" "jinja2" "j2" "jinja-html"))
    (treemacs-create-icon :file "sublime.png" :extensions ("sublime-project" "sublime-workspace"))
    (treemacs-create-icon :file "yaml.png" :extensions ("yaml" "YAML-tmLanguage" "yml" ".metadata" ".packages"))
    (treemacs-create-icon :file "xml.png" :extensions (".htaccess"))
    (treemacs-create-icon :file "javascript.png" :extensions ("js" "esx" "mjs"))
    (treemacs-create-icon :file "react.png" :extensions ("jsx" "tsx"))
    (treemacs-create-icon :file "settings.png" :extensions (".jshintignore" ".buildignore" ".mrconfig" ".yardopts" "manifest.mf" ".clang-format" ".clang-tidy"))
    (treemacs-create-icon :file "typescript.png" :extensions ("ts"))
    (treemacs-create-icon :file "typescript-def.png" :extensions ("d.ts"))
    (treemacs-create-icon :file "markojs.png" :extensions ("marko"))
    (treemacs-create-icon :file "pdf.png" :extensions ("pdf"))
    (treemacs-create-icon :file "table.png" :extensions ("xlsx" "xls" "csv" "tsv"))
    (treemacs-create-icon :file "vscode.png" :extensions ("vscodeignore" "vsixmanifest" "vsix" "code-workplace"))
    (treemacs-create-icon :file "visualstudio.png" :extensions ("csproj" "ruleset" "sln" "suo" "vb" "vbs" "vcxitems" "vcxitems.filters" "vcxproj" "vcxproj.filters"))
    (treemacs-create-icon :file "database.png" :extensions ("pdb" "sql" "pks" "pkb" "accdb" "mdb" "sqlite" "pgsql" "postgres" "psql"))
    (treemacs-create-icon :file "csharp.png" :extensions ("cs" "csx"))
    (treemacs-create-icon :file "image.png" :extensions ("jpg" "jpeg" "bmp" "svg" "png" "xpm" "gif"))
    (treemacs-create-icon :file "qsharp.png" :extensions ("qs"))
    (treemacs-create-icon :file "zip.png" :extensions ("zip" "tar" "gz" "xz" "br" "bzip2" "gzip" "brotli" "7z" "rar" "tgz"))
    (treemacs-create-icon :file "vala.png" :extensions ("vala"))
    (treemacs-create-icon :file "zig.png" :extensions ("zig"))
    (treemacs-create-icon :file "exe.png" :extensions ("exe" "msi"))
    (treemacs-create-icon :file "java.png" :extensions ("java" "jar" "jsp"))
    (treemacs-create-icon :file "c.png" :extensions ("c" "m" "i" "mi"))
    (treemacs-create-icon :file "h.png" :extensions ("h"))
    (treemacs-create-icon :file "cpp.png" :extensions ("cc" "cpp" "cxx" "c++" "cp" "mm" "mii" "ii"))
    (treemacs-create-icon :file "hpp.png" :extensions ("hh" "hpp" "hxx" "h++" "hp" "tcc" "inl"))
    (treemacs-create-icon :file "go.png" :extensions ("go"))
    (treemacs-create-icon :file "go-mod.png" :extensions ("go.mod" "go.sum"))
    (treemacs-create-icon :file "python.png" :extensions ("py"))
    (treemacs-create-icon :file "python-misc.png" :extensions ("requirements.txt" "pipfile" ".python-version" "manifest.in"))
    (treemacs-create-icon :file "url.png" :extensions ("url"))
    (treemacs-create-icon :file "console.png" :extensions ("sh" "ksh" "csh" "tcsh" "zsh" "bash" "bat" "cmd" "awk" "fish"))
    (treemacs-create-icon :file "powershell.png" :extensions ("ps1" "psm1" "psd1" "ps1xml" "psc1" "pssc"))
    (treemacs-create-icon :file "gradle.png" :extensions ("gradle.properties" "gradlew" "gradle-wrapper.properties"))
    (treemacs-create-icon :file "word.png" :extensions ("doc" "docx" "rtf"))
    (treemacs-create-icon :file "certificate.png" :extensions ("license" "license.md" "license.txt" "licence" "licence.md" "licence.txt" "unlicense" "unlicense.md" "unlicense.txt"))
    (treemacs-create-icon :file "key.png" :extensions (".htpasswd"))
    (treemacs-create-icon :file "font.png" :extensions ("woff" "woff2" "ttf" "eot" "suit" "otf" "bmap" "fnt" "odttf" "ttc" "font" "fonts" "sui" "ntf" "mrf"))
    (treemacs-create-icon :file "lib.png" :extensions ("lib" "bib"))
    (treemacs-create-icon :file "ruby.png" :extensions ("rb" "erb"))
    (treemacs-create-icon :file "gemfile.png" :extensions ("gemfile"))
    (treemacs-create-icon :file "fsharp.png" :extensions ("fs" "fsx" "fsi" "fsproj"))
    (treemacs-create-icon :file "swift.png" :extensions ("swift"))
    (treemacs-create-icon :file "arduino.png" :extensions ("ino"))
    (treemacs-create-icon :file "docker.png" :extensions ("dockerfile" "dockerfile.prod" "dockerfile.production" "docker-compose.yml" "docker-compose.yaml" "docker-compose.dev.yml" "docker-compose.local.yml" "docker-compose.ci.yml" "docker-compose.override.yml" "docker-compose.staging.yml" "docker-compose.prod.yml" "docker-compose.production.yml" "docker-compose.test.yml"))
    (treemacs-create-icon :file "tex.png" :extensions ("tex" "sty" "dtx" "ltx"))
    (treemacs-create-icon :file "powerpoint.png" :extensions ("pptx" "ppt" "pptm" "potx" "potm" "ppsx" "ppsm" "pps" "ppam" "ppa"))
    (treemacs-create-icon :file "video.png" :extensions ("webm" "mkv" "flv" "vob" "ogv" "ogg" "gifv" "avi" "mov" "qt" "wmv" "yuv" "rm" "rmvb" "mp4" "m4v" "mpg" "mp2" "mpeg" "mpe" "mpv" "m2v"))
    (treemacs-create-icon :file "virtual.png" :extensions ("vdi" "vbox" "vbox-prev"))
    (treemacs-create-icon :file "email.png" :extensions (".mailmap"))
    (treemacs-create-icon :file "audio.png" :extensions ("mp3" "flac" "m4a" "wma" "aiff"))
    (treemacs-create-icon :file "coffee.png" :extensions ("coffee" "cson" "iced"))
    (treemacs-create-icon :file "document.png" :extensions ("txt"))
    (treemacs-create-icon :file "graphql.png" :extensions (".graphqlconfig"))
    (treemacs-create-icon :file "rust.png" :extensions ("rs"))
    (treemacs-create-icon :file "raml.png" :extensions ("raml"))
    (treemacs-create-icon :file "xaml.png" :extensions ("xaml"))
    (treemacs-create-icon :file "haskell.png" :extensions ("hs"))
    (treemacs-create-icon :file "kotlin.png" :extensions ("kt" "kts"))
    (treemacs-create-icon :file "git.png" :extensions (".gitignore" ".gitconfig" ".gitattributes" ".gitmodules" ".gitkeep" "git-history"))
    (treemacs-create-icon :file "lua.png" :extensions (".luacheckrc"))
    (treemacs-create-icon :file "clojure.png" :extensions ("clj" "cljs" "cljc"))
    (treemacs-create-icon :file "groovy.png" :extensions ("groovy"))
    (treemacs-create-icon :file "r.png" :extensions (".Rhistory"))
    (treemacs-create-icon :file "dart.png" :extensions ("dart"))
    (treemacs-create-icon :file "actionscript.png" :extensions ("as"))
    (treemacs-create-icon :file "mxml.png" :extensions ("mxml"))
    (treemacs-create-icon :file "autohotkey.png" :extensions ("ahk"))
    (treemacs-create-icon :file "flash.png" :extensions ("swf"))
    (treemacs-create-icon :file "swc.png" :extensions ("swc"))
    (treemacs-create-icon :file "cmake.png" :extensions ("cmakelists.txt" "cmakecache.txt"))
    (treemacs-create-icon :file "assembly.png" :extensions ("asm" "a51" "inc" "nasm" "s" "ms" "agc" "ags" "aea" "argus" "mitigus" "binsource"))
    (treemacs-create-icon :file "vue.png" :extensions ("vue"))
    (treemacs-create-icon :file "vue-config.png" :extensions ("vue.config.js" "vue.config.ts"))
    (treemacs-create-icon :file "nuxt.png" :extensions ("nuxt.config.js" "nuxt.config.ts"))
    (treemacs-create-icon :file "ocaml.png" :extensions ("ml" "mli" "cmx"))
    (treemacs-create-icon :file "javascript-map.png" :extensions (".js.map" "mjs.map"))
    (treemacs-create-icon :file "css-map.png" :extensions ("css.map"))
    (treemacs-create-icon :file "lock.png" :extensions ("security.md" "security.txt" "security"))
    (treemacs-create-icon :file "handlebars.png" :extensions ("hbs" "mustache"))
    (treemacs-create-icon :file "perl.png" :extensions ("pm" "raku"))
    (treemacs-create-icon :file "haxe.png" :extensions ("hx"))
    (treemacs-create-icon :file "test-ts.png" :extensions ("spec.ts" "e2e-spec.ts" "test.ts" "ts.snap"))
    (treemacs-create-icon :file "test-jsx.png" :extensions ("spec.tsx" "test.tsx" "tsx.snap" "spec.jsx" "test.jsx" "jsx.snap"))
    (treemacs-create-icon :file "test-js.png" :extensions ("spec.js" "e2e-spec.js" "test.js" "js.snap"))
    (treemacs-create-icon :file "angular.png" :extensions ("angular-cli.json" ".angular-cli.json" "angular.json"))
    (treemacs-create-icon :file "puppet.png" :extensions ("pp"))
    (treemacs-create-icon :file "elixir.png" :extensions ("ex" "exs" "eex" "leex"))
    (treemacs-create-icon :file "livescript.png" :extensions ("ls"))
    (treemacs-create-icon :file "erlang.png" :extensions ("erl"))
    (treemacs-create-icon :file "twig.png" :extensions ("twig"))
    (treemacs-create-icon :file "julia.png" :extensions ("jl"))
    (treemacs-create-icon :file "elm.png" :extensions ("elm"))
    (treemacs-create-icon :file "purescript.png" :extensions ("pure" "purs"))
    (treemacs-create-icon :file "smarty.png" :extensions ("tpl"))
    (treemacs-create-icon :file "stylus.png" :extensions ("styl"))
    (treemacs-create-icon :file "reason.png" :extensions ("re" "rei"))
    (treemacs-create-icon :file "bucklescript.png" :extensions ("cmj"))
    (treemacs-create-icon :file "merlin.png" :extensions ("merlin"))
    (treemacs-create-icon :file "verilog.png" :extensions ("v" "vhd" "sv" "svh"))
    (treemacs-create-icon :file "mathematica.png" :extensions ("nb"))
    (treemacs-create-icon :file "wolframlanguage.png" :extensions ("wl" "wls"))
    (treemacs-create-icon :file "nunjucks.png" :extensions ("njk" "nunjucks"))
    (treemacs-create-icon :file "robot.png" :extensions ("robot"))
    (treemacs-create-icon :file "solidity.png" :extensions ("sol"))
    (treemacs-create-icon :file "autoit.png" :extensions ("au3"))
    (treemacs-create-icon :file "haml.png" :extensions ("haml"))
    (treemacs-create-icon :file "yang.png" :extensions ("yang"))
    (treemacs-create-icon :file "mjml.png" :extensions ("mjml"))
    (treemacs-create-icon :file "vercel.png" :extensions ("vercel.json" ".vercelignore" "now.json" ".nowignore"))
    (treemacs-create-icon :file "terraform.png" :extensions ("tf" "tf.json" "tfvars" "tfstate"))
    (treemacs-create-icon :file "laravel.png" :extensions ("blade.php" "inky.php"))
    (treemacs-create-icon :file "applescript.png" :extensions ("applescript" "ipa"))
    (treemacs-create-icon :file "cake.png" :extensions ("cake"))
    (treemacs-create-icon :file "cucumber.png" :extensions ("feature"))
    (treemacs-create-icon :file "nim.png" :extensions ("nim" "nimble"))
    (treemacs-create-icon :file "apiblueprint.png" :extensions ("apib" "apiblueprint"))
    (treemacs-create-icon :file "riot.png" :extensions ("riot" "tag"))
    (treemacs-create-icon :file "vfl.png" :extensions (".vfl"))
    (treemacs-create-icon :file "kl.png" :extensions (".kl"))
    (treemacs-create-icon :file "postcss.png" :extensions ("postcss.config.js" ".postcssrc.js" ".postcssrc" ".postcssrc.json" ".postcssrc.yml"))
    (treemacs-create-icon :file "todo.png" :extensions ("todo"))
    (treemacs-create-icon :file "coldfusion.png" :extensions ("cfml" "cfc" "lucee" "cfm"))
    (treemacs-create-icon :file "cabal.png" :extensions ("cabal"))
    (treemacs-create-icon :file "nix.png" :extensions ("nix"))
    (treemacs-create-icon :file "slim.png" :extensions ("slim"))
    (treemacs-create-icon :file "http.png" :extensions ("CNAME"))
    (treemacs-create-icon :file "restql.png" :extensions ("rql" "restql"))
    (treemacs-create-icon :file "kivy.png" :extensions ("kv"))
    (treemacs-create-icon :file "graphcool.png" :extensions ("project.graphcool"))
    (treemacs-create-icon :file "sbt.png" :extensions ("sbt"))
    (treemacs-create-icon :file "webpack.png" :extensions ("webpack.js" "webpack.ts" "webpack.base.js" "webpack.base.ts" "webpack.config.js" "webpack.config.ts" "webpack.common.js" "webpack.common.ts" "webpack.config.common.js" "webpack.config.common.ts" "webpack.config.common.babel.js" "webpack.config.common.babel.ts" "webpack.dev.js" "webpack.dev.ts" "webpack.development.js" "webpack.development.ts" "webpack.config.dev.js" "webpack.config.dev.ts" "webpack.config.dev.babel.js" "webpack.config.dev.babel.ts" "webpack.prod.js" "webpack.prod.ts" "webpack.production.js" "webpack.production.ts" "webpack.server.js" "webpack.server.ts" "webpack.client.js" "webpack.client.ts" "webpack.config.server.js" "webpack.config.server.ts" "webpack.config.client.js" "webpack.config.client.ts" "webpack.config.production.babel.js" "webpack.config.production.babel.ts" "webpack.config.prod.babel.js" "webpack.config.prod.babel.ts" "webpack.config.prod.js" "webpack.config.prod.ts" "webpack.config.production.js" "webpack.config.production.ts" "webpack.config.staging.js" "webpack.config.staging.ts" "webpack.config.babel.js" "webpack.config.babel.ts" "webpack.config.base.babel.js" "webpack.config.base.babel.ts" "webpack.config.base.js" "webpack.config.base.ts" "webpack.config.staging.babel.js" "webpack.config.staging.babel.ts" "webpack.config.coffee" "webpack.config.test.js" "webpack.config.test.ts" "webpack.config.vendor.js" "webpack.config.vendor.ts" "webpack.config.vendor.production.js" "webpack.config.vendor.production.ts" "webpack.test.js" "webpack.test.ts" "webpack.dist.js" "webpack.dist.ts" "webpackfile.js" "webpackfile.ts"))
    (treemacs-create-icon :file "ionic.png" :extensions ("ionic.config.json" ".io-config.json"))
    (treemacs-create-icon :file "gulp.png" :extensions ("gulpfile.js" "gulpfile.mjs" "gulpfile.ts" "gulpfile.babel.js"))
    (treemacs-create-icon :file "nodejs.png" :extensions ("package.json" "package-lock.json" ".nvmrc" ".esmrc" ".node-version"))
    (treemacs-create-icon :file "npm.png" :extensions (".npmignore" ".npmrc"))
    (treemacs-create-icon :file "yarn.png" :extensions (".yarnrc" "yarn.lock" ".yarnclean" ".yarn-integrity" "yarn-error.log" ".yarnrc.yml" ".yarnrc.yaml"))
    (treemacs-create-icon :file "android.png" :extensions ("androidmanifest.xml"))
    (treemacs-create-icon :file "tune.png" :extensions (".env.defaults" ".env.example" ".env.sample" ".env.schema" ".env.local" ".env.dev" ".env.development" ".env.qa" ".env.prod" ".env.production" ".env.staging" ".env.preview" ".env.test" ".env.testing" ".env.development.local" ".env.qa.local" ".env.production.local" ".env.staging.local" ".env.test.local"))
    (treemacs-create-icon :file "babel.png" :extensions (".babelrc" ".babelrc.js" ".babelrc.json" "babel.config.json" "babel.config.js"))
    (treemacs-create-icon :file "contributing.png" :extensions ("contributing.md"))
    (treemacs-create-icon :file "readme.png" :extensions ("readme.md" "readme.txt" "readme"))
    (treemacs-create-icon :file "changelog.png" :extensions ("changelog" "changelog.md" "changelog.txt" "changes" "changes.md" "changes.txt"))
    (treemacs-create-icon :file "credits.png" :extensions ("credits" "credits.txt" "credits.md"))
    (treemacs-create-icon :file "authors.png" :extensions ("authors" "authors.md" "authors.txt"))
    (treemacs-create-icon :file "flow.png" :extensions (".flowconfig"))
    (treemacs-create-icon :file "favicon.png" :extensions ("favicon.ico"))
    (treemacs-create-icon :file "karma.png" :extensions ("karma.conf.js" "karma.conf.ts" "karma.conf.coffee" "karma.config.js" "karma.config.ts" "karma-main.js" "karma-main.ts"))
    (treemacs-create-icon :file "bithound.png" :extensions (".bithoundrc"))
    (treemacs-create-icon :file "appveyor.png" :extensions (".appveyor.yml" "appveyor.yml"))
    (treemacs-create-icon :file "travis.png" :extensions (".travis.yml"))
    (treemacs-create-icon :file "codecov.png" :extensions (".codecov.yml" "codecov.yml"))
    (treemacs-create-icon :file "protractor.png" :extensions ("protractor.conf.js" "protractor.conf.ts" "protractor.conf.coffee" "protractor.config.js" "protractor.config.ts"))
    (treemacs-create-icon :file "fusebox.png" :extensions ("fuse.js"))
    (treemacs-create-icon :file "heroku.png" :extensions ("procfile" "procfile.windows"))
    (treemacs-create-icon :file "editorconfig.png" :extensions (".editorconfig"))
    (treemacs-create-icon :file "gitlab.png" :extensions ("gitlab-ci.yml"))
    (treemacs-create-icon :file "bower.png" :extensions (".bowerrc" "bower.json"))
    (treemacs-create-icon :file "eslint.png" :extensions (".eslintrc.js" ".eslintrc.cjs" ".eslintrc.yaml" ".eslintrc.yml" ".eslintrc.json" ".eslintrc" ".eslintignore" ".eslintcache"))
    (treemacs-create-icon :file "conduct.png" :extensions ("code_of_conduct.md" "code_of_conduct.txt"))
    (treemacs-create-icon :file "watchman.png" :extensions (".watchmanconfig"))
    (treemacs-create-icon :file "aurelia.png" :extensions ("aurelia.json"))
    (treemacs-create-icon :file "mocha.png" :extensions ("mocha.opts" ".mocharc.yml" ".mocharc.yaml" ".mocharc.js" ".mocharc.json" ".mocharc.jsonc"))
    (treemacs-create-icon :file "jenkins.png" :extensions ("jenkinsfile"))
    (treemacs-create-icon :file "firebase.png" :extensions ("firebase.json" ".firebaserc" "firestore.rules" "firestore.indexes.json"))
    (treemacs-create-icon :file "rollup.png" :extensions ("rollup.config.js" "rollup.config.ts" "rollup-config.js" "rollup-config.ts" "rollup.config.common.js" "rollup.config.common.ts" "rollup.config.base.js" "rollup.config.base.ts" "rollup.config.prod.js" "rollup.config.prod.ts" "rollup.config.dev.js" "rollup.config.dev.ts" "rollup.config.prod.vendor.js" "rollup.config.prod.vendor.ts"))
    (treemacs-create-icon :file "hack.png" :extensions (".hhconfig"))
    (treemacs-create-icon :file "stylelint.png" :extensions (".stylelintrc" "stylelint.config.js" ".stylelintrc.json" ".stylelintrc.yaml" ".stylelintrc.yml" ".stylelintrc.js" ".stylelintignore"))
    (treemacs-create-icon :file "code-climate.png" :extensions (".codeclimate.yml"))
    (treemacs-create-icon :file "prettier.png" :extensions (".prettierrc" "prettier.config.js" ".prettierrc.js" ".prettierrc.json" ".prettierrc.yaml" ".prettierrc.yml" ".prettierignore"))
    (treemacs-create-icon :file "apollo.png" :extensions ("apollo.config.js"))
    (treemacs-create-icon :file "nodemon.png" :extensions ("nodemon.json" "nodemon-debug.json"))
    (treemacs-create-icon :file "webhint.png" :extensions (".hintrc"))
    (treemacs-create-icon :file "browserlist.png" :extensions ("browserslist" ".browserslistrc"))
    (treemacs-create-icon :file "crystal.png" :extensions ("cr" "ecr"))
    (treemacs-create-icon :file "snyk.png" :extensions (".snyk"))
    (treemacs-create-icon :file "drone.png" :extensions (".drone.yml"))
    (treemacs-create-icon :file "cuda.png" :extensions ("cu" "cuh"))
    (treemacs-create-icon :file "log.png" :extensions ("log"))
    (treemacs-create-icon :file "dotjs.png" :extensions ("def" "dot" "jst"))
    (treemacs-create-icon :file "ejs.png" :extensions ("ejs"))
    (treemacs-create-icon :file "sequelize.png" :extensions (".sequelizerc"))
    (treemacs-create-icon :file "gatsby.png" :extensions ("gatsby.config.js" "gatsby-config.js" "gatsby-node.js" "gatsby-browser.js" "gatsby-ssr.js"))
    (treemacs-create-icon :file "wakatime.png" :extensions (".wakatime-project"))
    (treemacs-create-icon :file "circleci.png" :extensions ("circle.yml"))
    (treemacs-create-icon :file "cloudfoundry.png" :extensions (".cfignore"))
    (treemacs-create-icon :file "grunt.png" :extensions ("gruntfile.js" "gruntfile.ts" "gruntfile.coffee" "gruntfile.babel.js" "gruntfile.babel.ts" "gruntfile.babel.coffee"))
    (treemacs-create-icon :file "jest.png" :extensions ("jest.config.js" "jest.config.ts" "jest.config.cjs" "jest.config.mjs" "jest.config.json" "jest.e2e.config.js" "jest.e2e.config.ts" "jest.e2e.config.cjs" "jest.e2e.config.mjs" "jest.e2e.config.json" "jest.setup.js" "jest.setup.ts" "jest.json" ".jestrc" ".jestrc.js" ".jestrc.json" "jest.teardown.js"))
    (treemacs-create-icon :file "processing.png" :extensions ("pde"))
    (treemacs-create-icon :file "storybook.png" :extensions ("stories.js" "stories.jsx" "story.js" "story.jsx" "stories.ts" "stories.tsx" "story.ts" "story.tsx"))
    (treemacs-create-icon :file "wepy.png" :extensions ("wpy"))
    (treemacs-create-icon :file "fastlane.png" :extensions ("fastfile" "appfile"))
    (treemacs-create-icon :file "hcl.png" :extensions ("hcl"))
    (treemacs-create-icon :file "helm.png" :extensions (".helmignore"))
    (treemacs-create-icon :file "san.png" :extensions ("san"))
    (treemacs-create-icon :file "wallaby.png" :extensions ("wallaby.js" "wallaby.conf.js"))
    (treemacs-create-icon :file "django.png" :extensions ("djt"))
    (treemacs-create-icon :file "stencil.png" :extensions ("stencil.config.js" "stencil.config.ts"))
    (treemacs-create-icon :file "red.png" :extensions ("red"))
    (treemacs-create-icon :file "makefile.png" :extensions ("makefile"))
    (treemacs-create-icon :file "foxpro.png" :extensions ("fxp" "prg"))
    (treemacs-create-icon :file "i18n.png" :extensions ("pot" "po" "mo"))
    (treemacs-create-icon :file "webassembly.png" :extensions ("wat" "wasm"))
    (treemacs-create-icon :file "semantic-release.png" :extensions (".releaserc" ".releaserc.yaml" ".releaserc.yml" ".releaserc.json" ".releaserc.js" "release.config.js"))
    (treemacs-create-icon :file "bitbucket.png" :extensions ("bitbucket-pipelines.yaml" "bitbucket-pipelines.yml"))
    (treemacs-create-icon :file "jupyter.png" :extensions ("ipynb"))
    (treemacs-create-icon :file "d.png" :extensions ("d"))
    (treemacs-create-icon :file "mdx.png" :extensions ("mdx"))
    (treemacs-create-icon :file "ballerina.png" :extensions ("bal" "balx"))
    (treemacs-create-icon :file "racket.png" :extensions ("rkt"))
    (treemacs-create-icon :file "bazel.png" :extensions (".bazelignore" ".bazelrc"))
    (treemacs-create-icon :file "mint.png" :extensions ("mint"))
    (treemacs-create-icon :file "velocity.png" :extensions ("vm" "fhtml" "vtl"))
    (treemacs-create-icon :file "godot.png" :extensions ("gd"))
    (treemacs-create-icon :file "godot-assets.png" :extensions ("godot" "tres" "tscn"))
    (treemacs-create-icon :file "azure-pipelines.png" :extensions ("azure-pipelines.yml" "azure-pipelines.yaml"))
    (treemacs-create-icon :file "azure.png" :extensions ("azcli"))
    (treemacs-create-icon :file "vagrant.png" :extensions ("vagrantfile"))
    (treemacs-create-icon :file "prisma.png" :extensions ("prisma.yml"))
    (treemacs-create-icon :file "razor.png" :extensions ("cshtml" "vbhtml"))
    (treemacs-create-icon :file "abc.png" :extensions ("abc"))
    (treemacs-create-icon :file "asciidoc.png" :extensions ("ad" "adoc" "asciidoc"))
    (treemacs-create-icon :file "istanbul.png" :extensions (".nycrc" ".nycrc.json"))
    (treemacs-create-icon :file "edge.png" :extensions ("edge"))
    (treemacs-create-icon :file "scheme.png" :extensions ("ss" "scm"))
    (treemacs-create-icon :file "lisp.png" :extensions ("lisp" "lsp" "cl" "fast"))
    (treemacs-create-icon :file "tailwindcss.png" :extensions ("tailwind.js" "tailwind.config.js"))
    (treemacs-create-icon :file "3d.png" :extensions ("stl" "obj" "ac" "blend" "mesh" "mqo" "pmd" "pmx" "skp" "vac" "vdp" "vox"))
    (treemacs-create-icon :file "buildkite.png" :extensions ("buildkite.yml" "buildkite.yaml"))
    (treemacs-create-icon :file "netlify.png" :extensions ("netlify.json" "netlify.yml" "netlify.yaml" "netlify.toml"))
    (treemacs-create-icon :file "svelte.png" :extensions ("svelte"))
    (treemacs-create-icon :file "vim.png" :extensions ("vimrc" "gvimrc" "exrc"))
    (treemacs-create-icon :file "nest.png" :extensions ("nest-cli.json" ".nest-cli.json" "nestconfig.json" ".nestconfig.json"))
    (treemacs-create-icon :file "moonscript.png" :extensions ("moon"))
    (treemacs-create-icon :file "percy.png" :extensions (".percy.yml"))
    (treemacs-create-icon :file "gitpod.png" :extensions (".gitpod.yml"))
    (treemacs-create-icon :file "advpl_prw.png" :extensions ("prw" "prx"))
    (treemacs-create-icon :file "advpl_ptm.png" :extensions ("ptm"))
    (treemacs-create-icon :file "advpl_tlpp.png" :extensions ("tlpp"))
    (treemacs-create-icon :file "advpl_include.png" :extensions ("ch"))
    (treemacs-create-icon :file "codeowners.png" :extensions ("codeowners"))
    (treemacs-create-icon :file "gcp.png" :extensions (".gcloudignore"))
    (treemacs-create-icon :file "disc.png" :extensions ("iso"))
    (treemacs-create-icon :file "fortran.png" :extensions ("f" "f77" "f90" "f95" "f03" "f08"))
    (treemacs-create-icon :file "tcl.png" :extensions ("tcl"))
    (treemacs-create-icon :file "liquid.png" :extensions ("liquid"))
    (treemacs-create-icon :file "prolog.png" :extensions ("p" "pro"))
    (treemacs-create-icon :file "husky.png" :extensions (".huskyrc" "husky.config.js" ".huskyrc.json" ".huskyrc.js" ".huskyrc.yaml" ".huskyrc.yml"))
    (treemacs-create-icon :file "coconut.png" :extensions ("coco"))
    (treemacs-create-icon :file "tilt.png" :extensions ("tiltfile"))
    (treemacs-create-icon :file "capacitor.png" :extensions ("capacitor.config.json"))
    (treemacs-create-icon :file "sketch.png" :extensions ("sketch"))
    (treemacs-create-icon :file "pawn.png" :extensions ("pwn" "amx"))
    (treemacs-create-icon :file "adonis.png" :extensions (".adonisrc.json" "ace"))
    (treemacs-create-icon :file "forth.png" :extensions ("4th" "fth" "frt"))
    (treemacs-create-icon :file "uml.png" :extensions ("iuml" "pu" "puml" "plantuml" "wsd"))
    (treemacs-create-icon :file "meson.png" :extensions ("meson.build"))
    (treemacs-create-icon :file "commitlint.png" :extensions (".commitlintrc" ".commitlintrc.js" "commitlint.config.js" ".commitlintrc.json" ".commitlint.yaml" ".commitlint.yml"))
    (treemacs-create-icon :file "buck.png" :extensions (".buckconfig"))
    (treemacs-create-icon :file "dhall.png" :extensions ("dhall" "dhallb"))
    (treemacs-create-icon :file "sml.png" :extensions ("sml" "mlton" "mlb" "sig" "fun" "cm" "lex" "use" "grm"))
    (treemacs-create-icon :file "nrwl.png" :extensions ("nx.json"))
    (treemacs-create-icon :file "opam.png" :extensions ("opam"))
    (treemacs-create-icon :file "dune.png" :extensions ("dune" "dune-project"))
    (treemacs-create-icon :file "imba.png" :extensions ("imba"))
    (treemacs-create-icon :file "drawio.png" :extensions ("drawio" "dio"))
    (treemacs-create-icon :file "pascal.png" :extensions ("pas"))
    (treemacs-create-icon :file "shaderlab.png" :extensions ("unity"))
    (treemacs-create-icon :file "roadmap.png" :extensions ("roadmap.md" "roadmap.txt" "timeline.md" "timeline.txt" "milestones.md" "milestones.txt"))
    (treemacs-create-icon :file "sas.png" :extensions ("sas" "sas7bdat" "sashdat" "astore" "ast" "sast"))
    (treemacs-create-icon :file "nuget.png" :extensions ("nuget.config" ".nuspec" "nuget.exe"))
    (treemacs-create-icon :file "command.png" :extensions ("command"))
    (treemacs-create-icon :file "stryker.png" :extensions ("stryker.conf.js" "stryker.conf.json"))
    (treemacs-create-icon :file "denizenscript.png" :extensions ("dsc"))
    (treemacs-create-icon :file "modernizr.png" :extensions (".modernizrrc" ".modernizrrc.js" ".modernizrrc.json"))
    (treemacs-create-icon :file "slug.png" :extensions (".slugignore"))
    (treemacs-create-icon :file "search.png" :extensions ("code-search"))))

(treemacs-resize-icons 16)

(dolist (face '(treemacs-root-face
                treemacs-git-unmodified-face
                treemacs-git-modified-face
                treemacs-git-renamed-face
                treemacs-git-ignored-face
                treemacs-git-untracked-face
                treemacs-git-added-face
                treemacs-git-conflict-face
                treemacs-directory-face
                treemacs-directory-collapsed-face
                treemacs-file-face
                treemacs-tags-face))
  (set-face-attribute face nil :family "Noto Sans TC" :weight 'semi-light :height 100))

(provide 'treemacs-theme)
