#!/bin/sh

pkill sxhkd
sxhkd &

# Add nine workspaces
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 2
bspc config window_gap 10

pkill polybar
~/.config/polybar/launch.sh --docky
feh --no-fehbg --bg-scale ~/.local/share/backgrounds/bg.jpg

